model:
  base_learning_rate: 4.5e-06
  target: taming.models.cond_transformer.Net2NetTransformer
  params:
    cond_stage_key: scene_graph
    transformer_config:
      target: taming.modules.transformer.maskgpt.MASK_GPT
      params:
        vocab_size: 1024
        block_size: 512
        n_layer: 35
        n_head: 16
        n_embd: 1024
    first_stage_config:
      target: taming.models.vqgan.VQModel
      params:
        ckpt_path: logs/vqgan_imagenet_f16_1024/ckpts/last.ckpt
        embed_dim: 256
        n_embed: 1024
        ddconfig:
          double_z: false
          z_channels: 256
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 16
          dropout: 0.0
        lossconfig:
          target: taming.modules.losses.DummyLoss
    cond_stage_config:
      target: taming.modules.scene_graph.model.Scene_graph_encoder
      params:
        max_objects: 10

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 16
    collate_fn: taming.data.coco.coco_collate_fn
    train:
      target: taming.data.coco.CocoSceneGraph
      params:
        root_dir: /mnt/dataset/coco/cocodata
        image_dir_name: images/train2017
        instances_json_name: annotations/instances_train2017.json
        stuff_json_name: annotations/stuff_train2017.json
        image_size: 256
    validation:
      target: taming.data.coco.CocoSceneGraph
      params:
        root_dir: /mnt/dataset/coco/cocodata
        image_dir_name: images/val2017
        instances_json_name: annotations/instances_val2017.json
        stuff_json_name: annotations/stuff_val2017.json
        image_size: 256
